config/routes.rb
Privileges::Application.routes.draw do
  resources :collections

  resources :affiliations

  resources :emails

  resources :search

  resources :attendees do
    collection do
      post 'import'
    end
  end  

  resources :card_types

  resources :node_paths

  resources :borrowers do
    collection do
      post 'import'
      get 'confirmation'
      get 'country_select'
    end
  end  

  resources :events

  resources :nodes do
    collection do
      post 'import'
    end
  end

  devise_for :users
  
  resources :users

  root :to => "home#home"

end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
  belongs_to :event
  has_and_belongs_to_many :card_types
  has_and_belongs_to_many :affiliations
  has_and_belongs_to_many :collections
  belongs_to :attendee
  
  validates_presence_of :firstname, :lastname, :email, :phone, :event, :start_date, :end_date, :address_1, :city, :state, :zip, :country, :affiliations, :dob
  validates_uniqueness_of :email, :phone
  
  after_save :post_save_hooks
  
  def post_save_hooks
    rank = Hash.new
    self.affiliations.collect{|aff| rank[aff.rank] = aff.id}
    message = Affiliation.find(rank.sort[0][1]).message
    admin = User.find(:first, :conditions => {:admin => true})
    
    Email.create(
      :from => admin.email,
      :reply_to => admin.email,
      :to => self.email,
      :subject => "Privileges Request",
      :body => message
    )
      
  end
  
  def self.search(search)
    if search
      find(:all, :conditions => ['lower(email) LIKE ? or lower(lastname) LIKE ? or lower(firstname) LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
    end
  end
end

app/controllers/borrowers_controller.rb
require 'csv'
require 'carmen'
include Carmen

class BorrowersController < ApplicationController
  before_filter :authenticate_admin!, :except => [:new, :create, :confirmation, :country_select]

  def index
    @general_event = Event.find(:first, :conditions => {:name => "Privileges"})
    @borrowers = Borrower.find(:all, :conditions => {:event_id => @general_event.id})

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @borrower = Borrower.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @borrower = Borrower.new
    @event = Event.find(params[:event_id])

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @borrower = Borrower.find(params[:id])
    @event = @borrower.event
  end

  def create
    if params[:borrower][:event_id].nil?
      attendee = Attendee.find(:first, :conditions => {:email => params[:borrower][:email]})
      unless attendee.nil?
        params[:borrower][:attendee_id] = attendee.id
        @event = attendee.event
      else
        @event = Event.find(:first, :conditions => {:name => "Privileges"})
      end  
    else  
      @event = Event.find(params[:borrower][:event_id])
    end  

    params[:borrower][:event_id] = @event.id
    if params[:borrower][:start_date].nil? || params[:borrower][:start_date].blank?
      unless attendee.nil?
        params[:borrower][:start_date] = attendee.start_date
      else  
        params[:borrower][:start_date] = @event.start_date
      end
    else
      params[:borrower][:start_date] = Date.strptime(params[:borrower][:start_date], "%m/%d/%Y")
    end  
    if params[:borrower][:end_date].nil? || params[:borrower][:end_date].blank?
      unless attendee.nil?
        params[:borrower][:end_date] = attendee.end_date
      else  
        params[:borrower][:end_date] = @event.end_date
      end
    else
      params[:borrower][:end_date] = Date.strptime(params[:borrower][:end_date], "%m/%d/%Y")    
    end
    
    #strip all non numbers out of phone
    params[:borrower][:phone] = params[:borrower][:phone].gsub(/[^0-9]/, "")
    
    @borrower = Borrower.new(params[:borrower])
    respond_to do |format|
      if @borrower.save
        node_path = NodePath.new
        node_path.path = session[:node_path]
        node_path.borrower_id = @borrower.id
        node_path.session_id = session[:id]
        node_path.save
        #clear node_path session variable
        session[:node_path] = nil
        
        if current_user.try(:admin?)
          format.html { redirect_to borrowers_url, notice: 'Borrower was successfully created.' }    
        else
          format.html { redirect_to confirmation_borrowers_url(:id => @borrower.id), notice: 'Your information was successfully submitted.' }
        end
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @borrower = Borrower.find(params[:id])
    params[:borrower][:start_date] = Date.strptime(params[:borrower][:start_date], "%m/%d/%Y")
    params[:borrower][:end_date] = Date.strptime(params[:borrower][:end_date], "%m/%d/%Y")
    #strip all non numbers out of phone
    params[:borrower][:phone] = params[:borrower][:phone].gsub(/[^0-9]/, "")
    
    respond_to do |format|
      if @borrower.update_attributes(params[:borrower])
        if @borrower.event.is_general?
          format.html { redirect_to borrowers_url, notice: 'Borrower was successfully updated.' }
        else
          format.html { redirect_to event_url(@borrower.event), notice: 'Borrower was successfully updated.' }
        end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @borrower = Borrower.find(params[:id])
    @event = @borrower.event
    @borrower.destroy

    respond_to do |format|
      format.html { redirect_to event_url(@event) }
    end
  end
  
  def import
    event = params[:event_id]
    unless params[:upload].blank?
      @file = params[:upload][:datafile]
      CSV.parse(@file.read).each do |cell|
          borrower={}
          borrower[:event_id] = event
          borrower[:firstname] = cell[0]
          borrower[:middlename] = cell[1]
          borrower[:lastname] = cell[2]
          borrower[:email] = cell[3]
          borrower[:phone] = cell[4]
        
          @borrower = Borrower.new
          @borrower.attributes = borrower
          @borrower.save
      end
      redirect_to event_url(event)
    else
      redirect_to event_url(event), notice: 'No File Chosen'
    end    
  end
  
  def confirmation
    @borrower = Borrower.find(params[:id])
  end
  
  def country_select
    begin
       country = Carmen::country_code(params[:id])
       @states = Carmen::states(country)
    rescue
       @states = nil
    end
    render :partial => "states"
  end
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/views/borrowers/_form.html.erb
<% content_for :header_tags do %>
    <script type="text/javascript" charset="utf-8">
	  function change_state_select(country_code)
	 {
	    jQuery.get('<%= url_for(:controller => "borrowers", :action => "country_select") %>?id='+country_code,
	      	function (data) {
		        jQuery('#state_select').replaceWith(data);
	    });
	  }
	 </script>
	 <noscript>Please enable Javascript.</noscript>
<% end %>

<%= semantic_form_for(@borrower) do |f| %>
    <%= f.inputs do %>
	  <h4>Step 1: Please Check Current Affiliation:</h4>
	  <%= f.input :affiliations, :as => :check_boxes %>
	 
	  <h4>Step 2: If applicable, please check off the collections you wish to access:</h4>
	  <%= f.input :collections, :as => :check_boxes %>
	
	  <h4>Step 3: Registration Form:</h4>
	  <%= f.input :firstname, :label => "First Name " %>
	  <%= f.input :middlename, :label => "Middle Name " %>
	  <%= f.input :lastname, :label => "Last Name " %>
	  <%= f.input :address_1, :label => "Address 1 " %>
	  <%= f.input :address_2, :label => "Address 2 " %>
	  <%= f.input :city, :label => "City " %>
	  
	  Country<span class="required">*</span><br />
	  <%= f.select :country, Carmen::country_names, {:include_blank => true}, {:onchange => "change_state_select(this.options[this.selectedIndex].value);"} %>
	  </p>
	  <% unless @borrower.state.nil? %>
		<% begin %>
		  <%= render :partial => 'states', :locals => {:states => Carmen::states(Carmen::country_code(@borrower.country))} %>
		<% rescue %>
	      <%= render :partial => 'states', :locals => {:states => nil} %>
		<% end %>
	  <% else %>
	    <div id='state_select'></div>
	  <% end %>
	  <%= f.input :zip, :label => "Zip Code " %>
	  <%= f.input :email, :label => "Email " %>
	  <%= f.input :phone, :label => "Phone " %>
	  <%= f.input :dob, :label => "Date of Birth ", :start_year => Time.now.year, :end_year => Time.now.year - 100 %>
	  <% unless @event.nil? %>
	    <%= f.input :event_id, :as => :hidden, :value => @event.id %>
	  <% end %>
	
	  <h4>Step 4: Any other comments or questions:</h4>
	  <%= f.input :other, :label => "Other ", :input_html => { :class => 'autogrow', :rows => 8, :cols => 40 } %>
	
	  <% if current_user.try(:admin?) %>
	    <h4>Administrative</h4>
	    <% unless @borrower.start_date.nil? %>
	      <%= f.input :start_date, :label => "Start Date ", :as => :string, :input_html => { :value => @borrower.start_date.strftime("%m/%d/%Y")} %>
		<% else %>
		  <%= f.input :start_date, :label => "Start Date ", :as => :string %>
		<% end %>
		<% unless @borrower.end_date.nil? %>
	      <%= f.input :end_date, :label => "End Date ", :as => :string, :input_html => { :value => @borrower.end_date.strftime("%m/%d/%Y")} %>
		<% else %>
		  <%= f.input :end_date, :label => "End Date ", :as => :string %>
		<% end %>
		
	    <%= f.input :card_types, :as => :check_boxes, :label => "Card Type " %>
		<%= f.input :verified, :label => " This borrower has been verified." %>
	  <% end %>
	<% end %>
	<%= f.buttons do %>
	  <%= f.commit_button :label => "Submit Form" %>
	<% end %>
<% end %>


<script type="text/javascript" language="javascript">
	jQuery(document).ready(function(){
		jQuery("#borrower_start_date").datepicker({ minDate: 0 });
		jQuery("#borrower_end_date").datepicker({ minDate: 0 });
	})
</script>

app/views/borrowers/_list.html.erb
<table>
  <tr>
    <th>First</th>
    <th>Middle</th>
    <th>Last</th>
	<th>Email</th>
	<th>Phone</th>
	<th>Date of Birth</th>
	<th>Verified</th>
	<th>Actions</th>
  </tr>

<% borrowers.each do |borrower| %>
  <tr>
    <td><%= borrower.firstname %></td>
    <td><%= borrower.middlename %></td>
    <td><%= borrower.lastname %></td>
    <td><%= borrower.email %></td>
	<td><%= borrower.phone %></td>
	<td><%= borrower.dob %></td>
	<td><%= borrower.verified ? "Yes" : "No" %></td>
	<td><%= link_to 'View', borrower_path(borrower) %> | <%= link_to 'Edit', edit_borrower_path(borrower) %> | <%= link_to 'Destroy', borrower, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/borrowers/_states.html.erb
<p>
  	<div id="state_select">
	  State or Territory<br />
	  <% if !@borrower.nil? && !@borrower.state.nil? %>
	    <% if states.nil? %>
		  <%= text_field :borrower, :state %>
		<% else %>
		  <%= select :borrower, :state, states %>
		<% end %>
	  <% elsif @states.nil? %>
		<%= text_field :borrower, :state %>	
	  <% else %>
	    <%= select :borrower, :state, @states %>
	  <% end %>
	</div>
</p>

app/views/borrowers/confirmation.html.erb
<% content_for :header do %>Confirmation<% end %>
<p>
	<h3>Step 1: Affiliation(s)</h3>
	<% @borrower.affiliations.each do |aff| %>
	  <%= aff.name %><br />
	<% end %>
</p>
<p>
	<h3>Step 2: Collection(s)</h3>
	<% @borrower.collections.each do |coll| %>
	  <%= coll.name %><br />
	<% end %>
</p>
<p>
	<h3>Step 3: Registration Form</h3>
	First Name: <%= @borrower.firstname %><br />
    <%= @borrower.middlename.blank? ? '' : "Middle Name: #{@borrower.middlename}<br />" %>
    Last Name: <%= @borrower.lastname %><br />
	Address 1: <%= @borrower.address_1 %><br />
	<%= @borrower.address_2.blank? ? '' : "Address 2: #{@borrower.address_2}<br />" %>
	City: <%= @borrower.city %><br />
	State: <%= @borrower.state %><br />
	Zip: <%= @borrower.zip %><br />
	Country: <%= @borrower.country %><br /><br />
    Email: <%= @borrower.email %><br />
	Phone: <%= @borrower.phone %><br />
	Date of Birth: <%= @borrower.dob %>
</p>
<p>
	<h3>Step 4: Comments or Questions</h3>
	<%= @borrower.other %><br />
</p>

app/views/borrowers/edit.html.erb
<h1>Editing borrower</h1>

<%= render 'form' %>

<%= link_to 'Back', event_path(@borrower.event) %>

app/views/borrowers/index.html.erb
<% content_for :header do %>General Borrowers<% end %>
<div class="nodes collection-list">	
	<% if @general_event.nil? %>
	  <p>The general event for all borrowers has not been created yet.</p>
	<% elsif @borrowers.nil? || @borrowers.empty? %>
	  <p>There are no borrowers yet.</p>
	<% else %>
      <%= render :partial => "list", :locals => { :borrowers => @borrowers } %>
	<% end %>
  <p>
  <% if current_user.admin? %>
	<%= link_to 'New Borrower', new_borrower_path(:event_id => @general_event.id) %>
  <% end %>
  </p>
</div>

app/views/borrowers/new.html.erb
<% content_for :header do %>New Borrower for <%= @event.name %><% end %>

<%= render 'form' %>

<%= link_to 'Back', event_path(@event) %>

app/views/borrowers/show.html.erb
<% content_for :header do %>Borrower - <%= @borrower.firstname %> <%= @borrower.lastname %><% end %>
<p>
	<h3>Step 1: Affiliation(s)</h3>
	<% @borrower.affiliations.each do |aff| %>
	  <%= aff.name %><br />
	<% end %>
</p>
<p>
	<h3>Step 2: Collection(s)</h3>
	<% @borrower.collections.each do |coll| %>
	  <%= coll.name %><br />
	<% end %>
</p>	
<p>
	<h3>Step 3: Registration Form</h3>
	First Name: <%= @borrower.firstname %><br />
    <%= @borrower.middlename.blank? ? '' : "Middle Name: #{@borrower.middlename}<br />" %>
    Last Name: <%= @borrower.lastname %><br />
	Address 1: <%= @borrower.address_1 %><br />
	<%= @borrower.address_2.blank? ? '' : "Address 2: #{@borrower.address_2}<br />" %>
	City: <%= @borrower.city %><br />
	State: <%= @borrower.state %><br />
	Zip: <%= @borrower.zip %><br />
	Country: <%= @borrower.country %><br /><br />
    Email: <%= @borrower.email %><br />
	Phone: <%= @borrower.phone %><br />
	Date of Birth: <%= @borrower.dob %>
</p>
<p>
	<h3>Step 4: Comments or Questions</h3>
	<%= @borrower.other %><br />
</p>
<p>
	<h3>Administrative</h3>
	Event Association: <%= @borrower.event.name %><br />
	Start Date: <%= @borrower.start_date.strftime("%m/%d/%Y") %><br />
	End Date: <%= @borrower.end_date.strftime("%m/%d/%Y") %><br /><br />
	Card Type(s):<br />
	<% @borrower.card_types.each do |card| %>
	  <%= card.name %><br />
	<% end %>
    <br />
</p>	


<%= link_to 'Edit', edit_borrower_path(@borrower) %> |
<%= link_to 'Back', borrowers_path %>