config/routes.rb
Privileges::Application.routes.draw do
  resources :collections

  resources :affiliations

  resources :emails

  resources :search

  resources :attendees do
    collection do
      post 'import'
    end
  end  

  resources :card_types

  resources :node_paths

  resources :borrowers do
    collection do
      post 'import'
      get 'confirmation'
      get 'country_select'
    end
  end  

  resources :events

  resources :nodes do
    collection do
      post 'import'
    end
  end

  devise_for :users
  
  resources :users

  root :to => "home#home"

end

app/models/affiliation.rb
class Affiliation < ActiveRecord::Base
  has_and_belongs_to_many :borrowers
  
  validates_presence_of :name, :rank, :message
  validates_uniqueness_of :name, :rank
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :event
  
  validates_presence_of :firstname, :lastname, :email, :event
  
  def self.search(search)
    if search
      find(:all, :conditions => ['lower(email) LIKE ? or lower(lastname) LIKE ? or lower(firstname) LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
    end
  end
end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
  belongs_to :event
  has_and_belongs_to_many :card_types
  has_and_belongs_to_many :affiliations
  has_and_belongs_to_many :collections
  belongs_to :attendee
  
  validates_presence_of :firstname, :lastname, :email, :phone, :event, :start_date, :end_date, :address_1, :city, :state, :zip, :country, :affiliations, :dob
  validates_uniqueness_of :email, :phone
  
  after_save :post_save_hooks
  
  def post_save_hooks
    rank = Hash.new
    self.affiliations.collect{|aff| rank[aff.rank] = aff.id}
    message = Affiliation.find(rank.sort[0][1]).message
    admin = User.find(:first, :conditions => {:admin => true})
    
    Email.create(
      :from => admin.email,
      :reply_to => admin.email,
      :to => self.email,
      :subject => "Privileges Request",
      :body => message
    )
      
  end
  
  def self.search(search)
    if search
      find(:all, :conditions => ['lower(email) LIKE ? or lower(lastname) LIKE ? or lower(firstname) LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
    end
  end
end

app/models/card_type.rb
class CardType < ActiveRecord::Base
  has_and_belongs_to_many :borrowers
  
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_and_belongs_to_many :borrowers
  
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/email.rb
class Email < ActiveRecord::Base
  validates_presence_of :to, :from, :reply_to, :subject, :body
  
  def self.to_send
    self.find(:all, :conditions => {:message_sent => false}, :limit => EMAIL_BATCH_LIMIT)
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :borrowers
  has_many :attendees
  
  validates_presence_of :name, :start_date, :end_date
  validates_uniqueness_of :name
  
  def is_admin?(user)
    self.users.include?(user)
  end
  
  def is_general?
    self.name == "Privileges"
  end
  
  def self.search(search)
    if search
      find(:all, :conditions => ['lower(name) LIKE ?', "%#{search}%"])
    end
  end
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_and_belongs_to_many :choices, :class_name => 'Node', :foreign_key => 'choice_id', :join_table => 'choices_nodes'
  
  validates_presence_of :text
  validates_uniqueness_of :text
  
  def is_question?
    self.choices.length > 1
  end  
  
  def is_choice?
    self.choices.length == 1
  end
  
  def is_answer?
    self.choices.length <= 0
  end
end

app/models/node_path.rb
class NodePath < ActiveRecord::Base
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_and_belongs_to_many :events       

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
  
  def to_s
    %Q|#{email}|
  end
  
  def self.random_password(size = 11)
    chars = (('a'..'z').to_a + ('0'..'9').to_a) - %w(i o 0 1 l 0)
    (1..size).collect{|a| chars[rand(chars.size)] }.join
  end
end

app/controllers/nodes_controller.rb
require 'csv'

class NodesController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show]
  
  def index
    @nodes = Node.all
    @firsts = Node.find(:all, :conditions => {:first => true})

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @node = Node.find(params[:id])
    
    #saving user's flow chart choices to include in borrower object
    unless session[:node_path].nil?
      session[:node_path] += "," + @node.id.to_s
    else
      session[:node_path] = @node.id.to_s  
    end  

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @node = Node.find(params[:id])
  end

  def create
    @node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to nodes_url, notice: 'Node was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @node = Node.find(params[:id])
    @node.destroy
    
    respond_to do |format|
      flash[:notice] = %Q|Deleted node|
      format.html { redirect_to nodes_url }
    end
  end
  
  def import
    unless params[:upload].blank?
      @file = params[:upload][:datafile]
      CSV.parse(@file.read).each do |cell|
          node={}
          node[:text] = cell[0]
        
          @node = Node.new
          @node.attributes = node
          @node.save
      end
      redirect_to nodes_url
    else
      redirect_to nodes_url, notice: 'No File Chosen'
    end  
  end
  
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/helpers/card_types_helper.rb
module CardTypesHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/node_paths_helper.rb
module NodePathsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/nodes/_form.html.erb
<%= semantic_form_for(@node) do |f| %>
    <%= f.inputs do %>
      <%= f.input :text, :label => "Question Text: ", :input_html => {:rows => 3, :cols => 30} %>
	  <%= f.input :first, :label => " Is this the first question?" %>
	<% end %>
	
	<fieldset class="checkboxes">
    <%= label_tag "Choices:" %><br />
	<% all_nodes = Node.all(:order => 'id') %>
	<% unless all_nodes.blank? %>
	  <% for node in all_nodes %>
	      <% unless node == @node %>
		    <%= check_box_tag "node[choice_ids][]", node.id, @node.choices.include?(node) %>
	        <%= node.text %><br />
		  <% end %>	
	  <% end %>
	<% end %>
	</fieldset>
	<%= f.buttons %>
<% end %>

app/views/nodes/edit.html.erb
<div class="nodes collection-list">	
  <h2>Edit Node</h2>  
  <%= render :partial => 'form' %>
</div>

app/views/nodes/index.html.erb
<% content_for :header do %>Privileges<% end %>
<div class="nodes collection-list">
  <% unless @firsts.blank? %>
	<% unless @firsts.length == 1 %>
	  <h2>Choose a question to begin:</h2>
	<% else %>
	  <h2>Begin:</h2>
	<% end %>
	<p>
	  <% @firsts.each do |node| %>
	    <%= node.text %>
		<%= link_to('Go', node_path(node)) %>
		<br />
	  <% end %>
	</p>
  <% else %>
    <% if current_user.try(:admin?) %>
	  <h2 class="collapsable request-form">Privileges Request Form</h2>
	  <div class="node_list request-form-target">
	    <% @borrower = Borrower.new %>
	    <%= render 'borrowers/form' %>
	  </div>
	<% else %>
	  <h2>Privileges Request Form</h2>
	  <% @borrower = Borrower.new %>
	  <%= render 'borrowers/form' %>
	<% end %>
  <% end %> 
</div>		

<% if current_user.try(:admin?) %>
  <h2 class="collapsable node_list">View All Nodes</h2>
  <div class="node_list node_list-target">
	<% unless @nodes.blank? %>
		<p>
		  <% @nodes.each do |node| %>
		    <%= node.text %>
			<%= link_to('View', node_path(node)) %>
			<% if current_user.try(:admin?) %>
			  | <%= link_to('Edit', edit_node_path(node)) %>
			  | <%= link_to 'Destroy', node, confirm: 'Are you sure?', method: :delete %>
			<% end %>
			<br />
		  <% end %>
		</p>
	  <% else %>
		<h2>No nodes yet.</h2>
	  <% end %>
	  <p>
	    <%= link_to('New Node', new_node_path) %>
	  </p>
  </div>
	
  <h2 class="collapsable node_upload">Node Upload via CSV</h2>
  <div class="node_upload node_upload-target">
    <p>
      Use the form below to import nodes via a CSV (comma separated value) file. Do not use column headings or quotes around text in any field. Each row will be separated by a new line or carriage return.
    </p>
    <p>
      These are the fields to be populated:
	  <ul>
		<li>node</li>
	  </ul>
    </p>
    <p>
	  e.g. node
    </p>

    <%= form_tag import_nodes_path, :multipart => true do -%>
      <%= file_field 'upload', 'datafile' %></p>
	  <%= submit_tag "Upload CSV", :disable_with => 'Uploading...' %>
    <% end -%>
  </div>	
<% end %>

app/views/nodes/new.html.erb
<div class="nodes collection-list">	
  <h2>New Node</h2>  
  <%= render :partial => 'form' %>
  <p>
	<%= link_to 'Back', nodes_path %>
  </p>
</div>

app/views/nodes/show.html.erb
<div class="node show-object">
  <% if @node.is_question? %>
  	<p>
	  <%= @node.text %>
	  <% if current_user.try(:admin?) %>
	    <%= link_to('Edit', edit_node_path(@node)) %>
	  <% end %>	
	  <ul>
	    <% @node.choices.each do |choice| %>
		  <% unless choice.choices.nil? %>	
		    <li>
				<%= link_to choice.text, choice %>
				<% if current_user.try(:admin?) %>
				  <%= link_to('Edit', edit_node_path(choice)) %>
				<% end %>
			</li>
		  <% else %>
	        <li>
				<%= choice.text %>
				<% if current_user.try(:admin?) %>
				  <%= link_to('Edit', edit_node_path(choice)) %>
				<% end %>
			</li>
	      <% end %>
	    <% end %>
	  </ul>
	</p>
  <% elsif @node.is_choice? && !@node.choices[0].choices.blank? %>
    <p>
	  <%= @node.text %>
	  	<% if current_user.try(:admin?) %>
		  <%= link_to('Edit', edit_node_path(@node)) %>
		<% end %>
	  <br /><br />
	  <%= @node.choices[0].text %>
	  	<% if current_user.try(:admin?) %>
		  <%= link_to('Edit', edit_node_path(@node.choices[0])) %>
		<% end %>
	  <ul>
	    <% @node.choices[0].choices.each do |choice| %>
		  <% unless choice.choices.nil? %>	
		    <li>
				<%= link_to choice.text, choice %>
				<% if current_user.try(:admin?) %>
				  <%= link_to('Edit', edit_node_path(choice)) %>
				<% end %>
			</li>
		  <% else %>
	        <li>
				<%= choice.text %>
				<% if current_user.try(:admin?) %>
				  <%= link_to('Edit', edit_node_path(choice)) %>
				<% end %>
			</li>
	      <% end %>
	    <% end %>
	  </ul>
	</p>	
  <% else %>
	<p>
	  <% unless @node.choices.nil? || @node.choices.empty? %>
	    Result: <br/>
	    <%= @node.choices[0].text %>
		<% if current_user.try(:admin?) %>
		  <%= link_to('Edit', edit_node_path(@node.choices[0])) %>
		<% end %>
		<h2>Privileges Request</h2>
		<% @borrower = Borrower.new %>
		<%= render 'borrowers/form' %>
		</p>
	  <% end %>
	<p>
  <% end %>
</div>
<p>
	<% if current_user.try(:admin?) %>
	  <%= link_to "View All Nodes", nodes_path %>
	<% else %>
	  <%= link_to "Exit and Return to Home", "/" %>
	<% end %>
</p>	