config/routes.rb
Privileges::Application.routes.draw do
  resources :collections

  resources :affiliations

  resources :emails

  resources :search

  resources :attendees do
    collection do
      post 'import'
    end
  end  

  resources :card_types

  resources :node_paths

  resources :borrowers do
    collection do
      post 'import'
      get 'confirmation'
      get 'country_select'
    end
  end  

  resources :events

  resources :nodes do
    collection do
      post 'import'
    end
  end

  devise_for :users
  
  resources :users

  root :to => "home#home"

end

app/models/affiliation.rb
class Affiliation < ActiveRecord::Base
  has_and_belongs_to_many :borrowers
  
  validates_presence_of :name, :rank, :message
  validates_uniqueness_of :name, :rank
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :event
  
  validates_presence_of :firstname, :lastname, :email, :event
  
  def self.search(search)
    if search
      find(:all, :conditions => ['lower(email) LIKE ? or lower(lastname) LIKE ? or lower(firstname) LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
    end
  end
end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
  belongs_to :event
  has_and_belongs_to_many :card_types
  has_and_belongs_to_many :affiliations
  has_and_belongs_to_many :collections
  belongs_to :attendee
  
  validates_presence_of :firstname, :lastname, :email, :phone, :event, :start_date, :end_date, :address_1, :city, :state, :zip, :country, :affiliations, :dob
  validates_uniqueness_of :email, :phone
  
  after_save :post_save_hooks
  
  def post_save_hooks
    rank = Hash.new
    self.affiliations.collect{|aff| rank[aff.rank] = aff.id}
    message = Affiliation.find(rank.sort[0][1]).message
    admin = User.find(:first, :conditions => {:admin => true})
    
    Email.create(
      :from => admin.email,
      :reply_to => admin.email,
      :to => self.email,
      :subject => "Privileges Request",
      :body => message
    )
      
  end
  
  def self.search(search)
    if search
      find(:all, :conditions => ['lower(email) LIKE ? or lower(lastname) LIKE ? or lower(firstname) LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
    end
  end
end

app/models/card_type.rb
class CardType < ActiveRecord::Base
  has_and_belongs_to_many :borrowers
  
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_and_belongs_to_many :borrowers
  
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/email.rb
class Email < ActiveRecord::Base
  validates_presence_of :to, :from, :reply_to, :subject, :body
  
  def self.to_send
    self.find(:all, :conditions => {:message_sent => false}, :limit => EMAIL_BATCH_LIMIT)
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :borrowers
  has_many :attendees
  
  validates_presence_of :name, :start_date, :end_date
  validates_uniqueness_of :name
  
  def is_admin?(user)
    self.users.include?(user)
  end
  
  def is_general?
    self.name == "Privileges"
  end
  
  def self.search(search)
    if search
      find(:all, :conditions => ['lower(name) LIKE ?', "%#{search}%"])
    end
  end
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_and_belongs_to_many :choices, :class_name => 'Node', :foreign_key => 'choice_id', :join_table => 'choices_nodes'
  
  validates_presence_of :text
  validates_uniqueness_of :text
  
  def is_question?
    self.choices.length > 1
  end  
  
  def is_choice?
    self.choices.length == 1
  end
  
  def is_answer?
    self.choices.length <= 0
  end
end

app/models/node_path.rb
class NodePath < ActiveRecord::Base
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_and_belongs_to_many :events       

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
  
  def to_s
    %Q|#{email}|
  end
  
  def self.random_password(size = 11)
    chars = (('a'..'z').to_a + ('0'..'9').to_a) - %w(i o 0 1 l 0)
    (1..size).collect{|a| chars[rand(chars.size)] }.join
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!

  def index
    if current_user.try(:admin?)
      @events = Event.all
    elsif user_signed_in?
      @events = []
      Event.all.each do |event|
        if event.users.include?(current_user)
          @events << event 
        end  
      end  
    end      

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    params[:event][:start_date] = Date.strptime(params[:event][:start_date], "%m/%d/%Y")
    params[:event][:end_date] = Date.strptime(params[:event][:end_date], "%m/%d/%Y")
    @event = Event.new(params[:event])
    
    respond_to do |format|
      if @event.save
        format.html { redirect_to events_url, notice: 'Event was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @event = Event.find(params[:id])
    params[:event][:start_date] = Date.strptime(params[:event][:start_date], "%m/%d/%Y")
    params[:event][:end_date] = Date.strptime(params[:event][:end_date], "%m/%d/%Y")
    
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
    end
  end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/helpers/card_types_helper.rb
module CardTypesHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/node_paths_helper.rb
module NodePathsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= semantic_form_for(@event) do |f| %>
    <%= f.inputs do %>
	  <%= f.input :name, :label => "Event Name " %>
	  <%= f.input :description, :label => "Event Description ", :input_html => {:rows => 5, :cols => 30} %>
      <%= f.input :users, :as => :check_boxes, :label => "Event Admin " %>
	  <% if @event.start_date.nil? %>
	    <%= f.input :start_date, :label => "Start Date ", :as => :string, :input_html => { :value => Date.today.strftime("%m/%d/%Y") } %><br />
	  <% else %>
	    <%= f.input :start_date, :label => "Start Date ", :as => :string, :input_html => { :value => @event.start_date.strftime("%m/%d/%Y")} %><br />
	  <% end %>
	  <% unless @event.end_date.nil? %>
	    <%= f.input :end_date, :label => "End Date ", :as => :string, :input_html => { :value => @event.end_date.strftime("%m/%d/%Y")} %>
	  <% else %>
	    <%= f.input :end_date, :label => "End Date ", :as => :string %>
	  <% end %>
	  <br />
	  <%= f.input :canceled, :label => " Has this event been canceled?" %>
	<% end %>
	
	<%= f.buttons %>
<% end %>


<script type="text/javascript" language="javascript">
	jQuery(document).ready(function(){
		jQuery("#event_start_date").datepicker({ minDate: 0 });
		jQuery("#event_end_date").datepicker({ minDate: 0 });
	})
</script>

app/views/events/_list.html.erb
<table>
  <tr>
    <th>Name</th>
	<th>Start Date</th>
	<th>End Date</th>
	<th>Actions</th>
  </tr>

<% events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
	<td><%= event.start_date %></td>
	<td><%= event.end_date %></td>
	<td><%= link_to 'Edit', edit_event_path(event) %> | <%= link_to 'Destroy', event, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% content_for :header do %>Events<% end %>

<div class="events collection-list">	
  <% unless @events.blank? %>
	<p>
	  <% @events.each do |event| %>
	    <%= event.name %> <%= event.canceled ? "(CANCELED)" : "" %>
		<%= link_to('View', event_path(event)) %>
		<% if current_user.try(:admin?) %>
		  <%= link_to('Edit', edit_event_path(event)) %>
		  <%= link_to 'Destroy', event, confirm: 'Are you sure?', method: :delete %>
		<% end %>
		<br />
	  <% end %>
	</p>
  <% else %>
	<h2>No events yet.</h2>
  <% end %>

  <p>
	<%= link_to('New Event', new_event_path) %>
  </p>
</div>

app/views/events/new.html.erb
<% content_for :header do %>New Event<% end %>
<div class="nodes collection-list">	
  <%= render :partial => 'form' %>
  <p>
	<%= link_to 'Back', events_path %>
  </p>	
</div>

app/views/events/show.html.erb
<% content_for :header do %><%= @event.name %><% end %>
<p>
  Description: <br />
  <%= @event.description %><br /><br />
  Event Admin(s): <br />
	<% @event.users.each do |admin| %>
	  <%= admin.email %><br />
	<% end %>
  <br />	
  Start Date: <%= @event.start_date.strftime("%m/%d/%Y") %><br />
  End Date: <%= @event.end_date.strftime("%m/%d/%Y") %><br />
  <%= @event.canceled ? "***Event has been canceled." : "" %>
</p>

<p>
	<%= link_to('Edit Event', edit_event_path(@event)) %>
	<% if current_user.admin? %> 
	  | <%= link_to 'Destroy Event', @event, confirm: 'Are you sure?', method: :delete %>
	<% end %>
</p>

<h2 class="collapsable attendee_list">Attendees</h2>
<div class="attendee_list attendee_list-target">
	<%= render :partial => "attendees/list", :locals => { :attendees => @event.attendees } %>
	<br />
	<% if @event.is_admin?(current_user) || current_user.admin? %>
	  <%= link_to 'New Attendee', new_attendee_path(:event_id => @event.id) %>
    <% end %>
</div>

<% if current_user.admin? %>
	<h2 class="collapsable borrower_list">Borrowers</h2>
	<div class="borrower_list borrower_list-target">
		<%= render :partial => "borrowers/list", :locals => { :borrowers => @event.borrowers } %>
		<br />
		<% if @event.is_admin?(current_user) || current_user.admin? %>
		  <%= link_to 'New Borrower', new_borrower_path(:event_id => @event.id) %>
	    <% end %>
	</div>
<% end %>

<% if @event.is_admin?(current_user) || current_user.admin? %>
  <h2 class="collapsable attendee_upload">Attendee Upload via CSV</h2>
  <div class="attendee_upload attendee_upload-target">
    <p>
      Use the form below to import attendees via a CSV (comma separated value) file. All 5 fields (columns in excel) must be present even if they are left blank.
      Do not use column headings or quotes around text in any field. Each row will be separated by a new line or carriage return.
    </p>
    <p>
      These are the fields to be populated:
	  <ul>
		<li>firstname</li>
		<li>lastname</li>
		<li>email</li>
	  </ul>
    </p>
    <p>
	  e.g. firstname, lastname, email
    </p>

    <%= form_tag import_attendees_path, :multipart => true do -%>
      <%= file_field 'upload', 'datafile' %></p>
	  <%= hidden_field_tag :event_id, @event.id %>
	  <%= submit_tag "Upload CSV", :disable_with => 'Uploading...' %>
    <% end -%>
  </div>	
<% end %>